name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: code
      
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
         api-level: 33
         target: google_apis
         components: "platform-tools,platforms;android-33,system-images;android-33;google_apis;x86_64"


    # Run unit tests
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest


    - name: Start emulator and run UI tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
         api-level: 33
         target: google_apis
         arch: x86_64
         script: ./gradlew connectedDebugAndroidTest
         emulator-boot-timeout: 300
    

    
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: code
